apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels: 
    app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
spec:
  containers:
    - name: contianer-jenkins
      image: docker.io/amirayousef/jenkins-amira
      ports:
        - contianerPort: 8080 
